Gst-vaapi support av1 decode 8bit
intel/vaapi-fits pull request #226
Opened 2020-09-16 07:46 UTC by FocusLuo

Gst-vaapi support av1 decode 8bit

2020-09-20 03:34 UTC, FocusLuo commented
depend two gst patches merged as below:
gst-vaapi:
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/merge_requests/191
gst-plugins-bad:
https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/merge_requests/1464

2020-10-21 21:48 UTC, uartie requested changes
Please rebase since #238

2020-10-21 21:48 UTC, uartie commented on test/gst-vaapi/decode/av1.py
> +from ..util import *
Since #238, please use `from ....lib.gstreamer.vaapi.util import *`

2020-10-21 21:48 UTC, uartie commented on test/gst-vaapi/decode/av1.py
> +from .decoder import DecoderTest
Since #238, please use `from ....lib.gstreamer.vaapi.decoder import DecoderTest`

2020-10-21 21:50 UTC, uartie commented on test/gst-vaapi/util.py
> +    },
Since #238, this file has moved to lib/gstreamer/vaapi/util.py

2021-01-13 10:18 UTC, FocusLuo commented
Artie, with gst-vaapi merged several days ago, can you help to change the status of this patch?

2021-01-13 19:14 UTC, uartie approved these changes

2021-01-14 01:42 UTC, merged