gst-vaapi: added 12bit 422(Y212) support
intel/vaapi-fits pull request #228
Opened 2020-09-18 08:29 UTC by FocusLuo

hevc added 12bit 422(Y212) support

Signed-off-by: Luo Focus <focus.luo@intel.com>

2020-09-18 08:32 UTC, FocusLuo commented
This pull depends on:
vaapi-fits:  PR https://github.com/intel/vaapi-fits/pull/227
gst-vaapi:  PR https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/merge_requests/390

2020-10-21 21:52 UTC, uartie requested changes
Please rebase since #238

2020-10-21 21:52 UTC, uartie commented on test/gst-vaapi/util.py
> +    "Y212"  : ("y212-le", "Y212_LE"),
Since #238, this file has moved to lib/gstreamer/vaapi/util.py

2020-12-08 07:37 UTC, FocusLuo commented
All of this pull depends on had been merged:
vaapi-fits: PR #227
gst-vaapi: PR https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/merge_requests/390

2020-12-08 18:47 UTC, merged