ffmpeg-qsv decode vp9 12bit 420 support
intel/vaapi-fits pull request #244
Opened 2020-11-02 03:47 UTC by FocusLuo

2020-11-02 06:30 UTC, uartie requested changes

2020-11-02 06:30 UTC, uartie commented on test/ffmpeg-qsv/decode/12bit/vp9.py
> +### Copyright (C) 2018-2019 Intel Corporation
copyright year 2020.

2020-11-03 02:22 UTC, FocusLuo commented on test/ffmpeg-qsv/decode/12bit/vp9.py
> +### Copyright (C) 2018-2019 Intel Corporation
Updated, thanks reviewing

2020-11-03 03:01 UTC, uartie approved these changes
LGTM

2020-11-04 00:54 UTC, merged