Update the command  for av1 decoding.
intel/vaapi-fits pull request #274
Opened 2021-03-04 08:28 UTC by fanli-hub

ivfparse is actually a demuxer, and av1parse is required after ivfparse.

2021-03-04 09:22 UTC, uartie requested changes
We also need to add av1parse to 10bit test and same for gst-vaapi tests.

2021-03-04 09:22 UTC, uartie commented on test/gst-msdk/decode/av1.py
> +    dxmap = {".ivf" : "ivfparse", ".av1" : "ivfparse ! av1parse ", ".webm" : "matroskademux"}
`av1parse` should be added after all demuxers.  Thus, it would be better to just prepend before `msdkav1dec` in the gstdecoder setting on line 32.

2021-03-05 00:40 UTC, xhaihao commented
Do we have cases transcoding AV1 to other codecs? If yes, `av1parse` should be added for av1 transcoding too.

2021-03-31 19:18 UTC, uartie commented
@fanli-hub please respond to comments

2021-04-01 07:58 UTC, fanli-hub commented
We don't have transcode av1.

2021-04-01 08:35 UTC, uartie requested changes

2021-04-01 08:35 UTC, uartie commented on test/gst-msdk/decode/av1.py
> +    dxmap = {".ivf" : "ivfparse", ".av1" : "ivfparse ", ".webm" : "matroskademux"}
whitespace change is unnecessary

2021-04-01 18:28 UTC, uartie requested changes
Please squash your commits into one commit.

2021-04-02 01:05 UTC, xhaihao commented
@fanli-hub your patch looks good to me, btw will you consider to add transcoding cases for AV1?

2021-04-07 17:11 UTC, uartie commented
@fanli-hub your first commit makes a change to dxmap, but the second commit reverts that change.  Thus, please squash both commits into one commit.

2021-04-16 15:58 UTC, merged