ffmpeg-d3d11: add av1.py for ffmpeg-d3d11
intel/vaapi-fits pull request #366
Opened 2022-01-06 08:12 UTC by tong1wu

add av1.py to enable 8bit av1 test cases

Signed-off-by: Tong Wu <tong1.wu@intel.com>

2022-01-06 19:48 UTC, uartie requested changes

2022-01-06 19:48 UTC, uartie commented on test/ffmpeg-d3d11/decode/av1.py
> +### Copyright (C) 2021 Intel Corporation
copyright year should be 2022

2022-01-07 01:09 UTC, tong1wu commented on test/ffmpeg-d3d11/decode/av1.py
> +### Copyright (C) 2021 Intel Corporation
> copyright year should be 2022

Modified, thanks.

2022-01-07 01:58 UTC, uartie approved these changes
LGTM thanks

2022-01-07 01:58 UTC, merged