enable max frame size for avc enc
intel/vaapi-fits pull request #398
Opened 2022-04-27 04:01 UTC by yefengxx

lib/parameters: add function for max_frame_size
ffmpeg-qsv: add max_frame_size for avc enc
gst-msdk: add max_frame_size for avc enc

Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

2022-04-27 04:01 UTC, yefengxx commented
@uartie @FocusLuo can you review this for me?

2022-05-16 20:19 UTC, uartie requested changes

2022-05-16 20:19 UTC, uartie commented on lib/gstreamer/encoderbase.py
> +      " -i {encoder.encoded} -show_frames | grep pkt_size".format(**vars(self)))
We can't assume ffprobe is available in gstreamer tests.  Our CI does not install ffmpeg when it runs the gstreamer tests.

2022-05-23 06:29 UTC, yefengxx commented
https://github.com/intel/vaapi-fits/pull/402

2022-05-23 06:29 UTC, closed without merging