ffmpeg-qsv: add wa_ldb to allow b_strategy disable
intel/vaapi-fits pull request #405
Opened 2022-05-27 17:00 UTC by yefengxx

ffmpeg-qsv: add wa_ldb to allow b_strategy disable

Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

2022-05-27 18:34 UTC, yefengxx commented
@uartie @FocusLuo can you review this for me?

2022-06-01 21:50 UTC, uartie approved these changes

2022-06-01 21:54 UTC, uartie commented
@yefengxx please update commit message to reflect the change made.  No need to mention "quality".  How about `ffmpeg-qsv: add wa_ldb to allow b_strategy disable`

2022-06-01 21:55 UTC, uartie requested changes
commit title

2022-06-05 14:47 UTC, yefengxx commented
> ffmpeg-qsv: add wa_ldb to allow b_strategy disable

thanks for your advice.

2022-06-05 14:48 UTC, yefengxx commented
> @yefengxx please update commit message to reflect the change made. No need to mention "quality". How about `ffmpeg-qsv: add wa_ldb to allow b_strategy disable`

thanks for your advice.

2022-06-06 13:22 UTC, uartie commented
> > @yefengxx please update commit message to reflect the change made. No need to mention "quality". How about `ffmpeg-qsv: add wa_ldb to allow b_strategy disable`
> 
> @uartie thanks for your advice.

Please update the commit message, not just the PR title.

2022-07-21 15:27 UTC, uartie commented on lib/ffmpeg/encoderbase.py
> +        opts += " -b_strategy 1"
@FocusLuo @feiwan1 is this workaround still needed, or can we delete it now?

2022-08-08 21:32 UTC, uartie commented on lib/ffmpeg/encoderbase.py
> +        opts += " -b_strategy 1"
removed in #433

2022-08-08 21:32 UTC, closed without merging