vah265enc:add hevc-8 and modify bitrate for gst-va
intel/vaapi-fits pull request #414
Opened 2022-07-02 10:39 UTC by yefengxx

1. add hevc-8 into mapprofile.
2. change the value of bitrate from maxrate to minrate.

Signed-off-by: Xu Yefeng <yefengx.xu@intel.com>

2022-07-02 10:43 UTC, yefengxx commented
@uartie  @FocusLuo  can you review this for me? 
According to He,Junyan , the value of bitrate for va encoder should be target bitrate(not maxrate), so I change it in this PR.

2022-07-05 16:21 UTC, uartie requested changes

2022-07-05 16:21 UTC, uartie commented on lib/gstreamer/va/util.py
> +    },
10 and 12 bit profiles do not go in "hevc-8".
Also, this work is already being done in #412 and will conflict with it.

2022-07-18 18:29 UTC, uartie commented
superseded by #422

2022-07-18 18:29 UTC, closed without merging