lib/gstreamer: use exe2os and filepath2os
intel/vaapi-fits pull request #420
Opened 2022-07-14 09:18 UTC by tong1wu

Signed-off-by: Tong Wu <tong1.wu@intel.com>

2022-07-20 00:43 UTC, uartie commented
@tong1wu please fix test regressions.  HINT: don't use f-strings in `gen_xxx` functions.  The `gen_xxx` functions usually only return a "templated" string to be formatted later by caller.  That is, caller may use different values with the same returned template (e.g. r2r).

2022-07-20 07:47 UTC, tong1wu commented
> @tong1wu please fix test regressions. HINT: don't use f-strings in `gen_xxx` functions. The `gen_xxx` functions usually only return a "templated" string to be formatted later by caller. That is, caller may use different values with the same returned template (e.g. r2r).

Thanks for pointing out. I have replaced the f-strings with a new variable. Please help review again. Thanks.

2022-07-20 17:51 UTC, uartie requested changes
Still alot of test failures.  Please don't use `self.decoded`, etc. in `gen_xxx` functions at all.  It might help to look at the ffmpeg classes to see how this is achieved for windows support.

2022-07-20 17:55 UTC, uartie commented on lib/gstreamer/vppbase.py
> +    self.osdecoded = filepath2os(self.decoded)
This should only be done in the `vpp()` function each time after `self.decoded` is assigned.

2022-07-20 17:58 UTC, uartie commented on lib/gstreamer/vppbase.py
> +    self.osdecoded = filepath2os(self.decoded)
I know the current design can be confusing to know when and where certain variables should be accessed.  I'm hoping to clean this confusion up in some upcoming refactors soon.  In the meantime, we just have to be careful.

2022-07-20 21:28 UTC, uartie commented
I've changed this to "draft" since it's clear it has not been properly verified locally nor any help requested.

Once you're confident it works for you locally, you can switch it back to "ready for review".  If you need any help, I'd be happy to answer your questions... just ask.

2022-07-21 07:04 UTC, tong1wu commented
Tested all components. The can work now. Ready for review thanks.

2022-07-26 13:05 UTC, uartie approved these changes

2022-07-26 13:05 UTC, merged