Remove vpp/sharpen/yv12 on >= gen12 platform
intel/vaapi-fits pull request #425
Opened 2022-07-20 09:09 UTC by fanli-hub

1. According to media-driver wiki, vpp/sharpen/yv12 input/output format does not support on >= gen12 platform. Remove vpp/sharpen/yv12 output format on >= gen12 platform
2. Remove vpp/sharpen/I420 input/output format on >= gen12 platform

2022-07-20 17:31 UTC, uartie requested changes

2022-07-20 17:31 UTC, uartie commented on lib/gstreamer/vppbase.py
> +
This is not needed.  Please remove this code change.

If the HW does not support the format directly, then the test will automatically insert compatible SW conversions into the pipeline.

2022-07-21 13:05 UTC, uartie commented
Please justify why `I420` removed, too.

2022-07-22 01:45 UTC, fanli-hub commented
Media driver also does not support vpp/sharpen I420 input/output on >= gen12 platform.

2022-07-22 12:43 UTC, uartie approved these changes

2022-07-23 16:02 UTC, FocusLuo approved these changes
LGTM

2022-07-23 16:02 UTC, merged