[Gst-va] add Vpp crop support
intel/vaapi-fits pull request #516
Opened 2023-06-08 08:58 UTC by wenqingx

2023-06-08 13:26 UTC, uartie requested changes
This is incomplete.  The crop parameters also need to be mapped to the gst-va command-line in `lib/gstreamer/va/vpp.py:gen_vpp_opts(...)`.  See `lib/gstreamer/vaapi/vpp.py` for an example.

2023-06-08 13:58 UTC, uartie commented on test/gst-va/vpp/crop.py
> +    super(default, self).before()
`super().before()` is better

2023-06-08 14:06 UTC, uartie commented
> This is incomplete. The crop parameters also need to be mapped to the gst-va command-line in `lib/gstreamer/va/vpp.py:gen_vpp_opts(...)`. See `lib/gstreamer/vaapi/vpp.py` for an example.

Ah, actually the vapostproc plugin uses crop meta for crop support.  Thus, we need to insert a videocrop before the vapostproc.  This can be done inside the `lib/gstreamer/va/vpp.py:gen_output_opts(...)` function override.

2023-06-08 14:07 UTC, uartie commented
https://gstreamer.freedesktop.org/documentation/va/vapostproc.html?gi-language=c#cropping-example

2023-06-08 14:13 UTC, uartie commented
> > This is incomplete. The crop parameters also need to be mapped to the gst-va command-line in `lib/gstreamer/va/vpp.py:gen_vpp_opts(...)`. See `lib/gstreamer/vaapi/vpp.py` for an example.
> 
> Ah, actually the vapostproc plugin uses crop meta for crop support. Thus, we need to insert a videocrop before the vapostproc. This can be done inside the `lib/gstreamer/va/vpp.py:gen_output_opts(...)` function override.

Also, we should set `disable-passthrough=true` to force vapostproc to handle the cropping instead of passing to downstream.

2023-06-14 02:59 UTC, wenqingx commented
thanks for review, and Focus help to do this part.closed. https://github.com/intel/vaapi-fits/pull/522

2023-06-14 02:59 UTC, closed without merging