MTL+ add encode vp9 10bit non-lowpower test path support
intel/vaapi-fits pull request #560
Opened 2023-09-25 03:37 UTC by FocusLuo

1, ffmpeg/gstreamer test add vp9-10bit non-lowpower mode support
2, ffmpeg/gstreamer lib update check for vp9-10bit non-lowpower
3, MTL caps

2023-09-25 16:39 UTC, uartie requested changes
We can do better... this is too hacked and confusing

2023-09-26 11:38 UTC, FocusLuo commented on lib/ffmpeg/encoderbase.py
> +         return 0
updated, thanks

2023-09-26 11:38 UTC, FocusLuo commented on lib/ffmpeg/vaapi/encoder.py
> +      "|Using intra and P-frames|[L|l]ow delay|forward-prediction"
updated, thanks review

2023-09-26 11:38 UTC, FocusLuo commented on test/gst-vaapi/encode/10bit/vp9.py
> +      _lowpower_ = False
updated, thanks review

2023-09-26 11:39 UTC, FocusLuo commented
> We can do better... this is too hacked and confusing

updated, thanks review

2023-09-26 11:41 UTC, FocusLuo commented
user@P12SL03SLIM50:/tmp_sda4/work_focus/applications.media.middleware.validation.vaapi-fits-smoke$ ./smoke run test/gst-va/encode/10bit/vp9.py --pl MTL --context=sanity -vv; ./smoke run test/gst-msdk/encode/10bit/vp9.py --pl MTL --context=sanity -vv; ./smoke run test/ffmpeg-vaapi/encode/10bit/vp9.py --pl MTL --context=sanity -vv; ./smoke run test/ffmpeg-qsv/encode/10bit/vp9.py --pl MTL --context=sanity -vv;
all passed

2023-09-26 17:51 UTC, uartie commented
please check test failures

2023-09-26 19:08 UTC, uartie requested changes

2023-09-26 19:08 UTC, uartie commented on test/ffmpeg-qsv/encode/10bit/vp9.py
> +  @parametrize_with_unused(*gen_vp9_cqp_lp_parameters(spec), ['refmode', 'loopshp', 'looplvl'])
wrong case variant generators.

2023-09-28 05:17 UTC, FocusLuo commented on lib/ffmpeg/vaapi/encoder.py
> +      _VAEntrypoint_Encode_Mode_ = "VAEntrypointEncSlice"
updated

2023-09-28 05:17 UTC, FocusLuo commented on lib/gstreamer/encoderbase.py
> +         return 0
updated

2023-09-28 05:18 UTC, FocusLuo commented
> please check test failures

depend on https://github.com/intel/vaapi-fits/pull/565  (lib/parameters.py file)

2023-09-28 05:18 UTC, FocusLuo commented on test/ffmpeg-qsv/encode/10bit/vp9.py
> +  @parametrize_with_unused(*gen_vp9_cqp_lp_parameters(spec), ['refmode', 'loopshp', 'looplvl'])
updated

2023-09-28 15:29 UTC, uartie commented
CI pre-check autogenerated 10-bit VP9 CQP cases and it looks like they all fail on i965 driver.  Thus, they will fail in sanity/full, too.  I see the i965 caps for KBL/CFL both include VME VP9 10bit... does i965 "actually" support it?

Also, please add case definitions to our BAT (pre-check) suite, otherwise >200 CQP cases will get generated automatically for each component.

2023-09-28 18:39 UTC, uartie commented
>  I see the i965 caps for KBL/CFL both include VME VP9 10bit... does i965 "actually" support it?

Nope... https://github.com/intel/vaapi-fits/pull/566

2023-09-29 19:25 UTC, uartie commented
Awaiting PR for BAT (pre-check).

2023-10-02 13:55 UTC, uartie commented
> Awaiting PR for BAT (pre-check).

https://github.com/intel-innersource/applications.media.middleware.validation.vaapi-fits-smoke/pull/354

2023-10-02 13:57 UTC, merged