[MTL+] add non-low power mode support for av1 10bit encode
intel/vaapi-fits pull request #563
Opened 2023-09-26 12:36 UTC by FocusLuo

1, add ffmpeg-vaapi/qsv support
2, add gst-va/msdk support
3, enable in caps

2023-09-26 12:38 UTC, FocusLuo commented
almost all sanity test cases passed except 1 case failed by bit rate check for gst-va

2023-09-26 19:09 UTC, uartie requested changes

2023-09-26 19:09 UTC, uartie commented on test/ffmpeg-qsv/encode/10bit/av1.py
> +  @slash.parametrize(*gen_av1_cqp_lp_parameters(spec))
wrong case variant generators.

2023-09-27 19:07 UTC, uartie commented
please fix conflicts

2023-09-28 15:34 UTC, uartie approved these changes

2023-09-28 15:36 UTC, merged