test/ffmpeg: add vpp/csc r2r test
intel/vaapi-fits pull request #582
Opened 2023-11-15 06:01 UTC by Hangjie22Coder

2023-11-16 17:07 UTC, uartie requested changes
Please split your changes into multiple commits... one for each middleware.

Additionally, commit messages should always have an empty line between the title and the message body.  Otherwise, mulitple lines in title will be concat as one line in git logs.... and that makes them hard to read.

2023-11-16 17:07 UTC, uartie commented on test/ffmpeg-qsv/vpp/csc.py
> +    self.vpp()
Please add empty new line at end of file.

2023-11-16 17:07 UTC, uartie commented on test/ffmpeg-vaapi/vpp/csc.py
> +    self.vpp()
Please add empty new line at end of file.

2023-11-16 17:07 UTC, uartie commented on test/gst-msdk/vpp/csc.py
> +    self.vpp()
Please add empty new line at end of file.

2023-11-16 17:07 UTC, uartie commented on test/gst-va/vpp/csc.py
> +    self.vpp()
Please add empty new line at end of file.

2023-11-16 17:07 UTC, uartie commented on test/gst-vaapi/vpp/csc.py
> +    self.vpp()
Please add empty new line at end of file.

2023-11-17 09:36 UTC, Hangjie22Coder commented
> Please split your changes into multiple commits... one for each middleware.
> 
> Additionally, commit messages should always have an empty line between the title and the message body. Otherwise, mulitple lines in title will be concat as one line in git logs.... and that makes them hard to read.

Thanks for the review, updated.

2023-11-17 15:56 UTC, uartie approved these changes

2023-11-17 15:56 UTC, merged