test/ffmpeg/gstreamer: add vpp/sharpen r2r test
intel/vaapi-fits pull request #587
Opened 2023-11-22 09:02 UTC by Hangjie22Coder

2023-11-27 15:24 UTC, uartie requested changes

2023-11-27 15:24 UTC, uartie commented on test/ffmpeg-qsv/vpp/sharpen.py
> +    vars(self).update(spec[case].copy())
Should be `spec_r2r`

2023-11-27 15:24 UTC, uartie commented on test/ffmpeg-vaapi/vpp/sharpen.py
> +    vars(self).update(spec[case].copy())
Should be `spec_r2r`

2023-11-27 15:24 UTC, uartie commented on test/gst-msdk/vpp/sharpen.py
> +    vars(self).update(spec[case].copy())
Should be `spec_r2r`

2023-11-27 15:24 UTC, uartie commented on test/gst-va/vpp/sharpen.py
> +    vars(self).update(spec[case].copy())
Should be `spec_r2r`

2023-11-27 15:24 UTC, uartie commented on test/gst-vaapi/vpp/sharpen.py
> +    vars(self).update(spec[case].copy())
Should be `spec_r2r`

2023-11-28 03:14 UTC, Hangjie22Coder commented on test/gst-vaapi/vpp/sharpen.py
> +    vars(self).update(spec[case].copy())
Thanks for the review, updated.

2023-11-28 21:32 UTC, uartie approved these changes

2023-11-28 21:33 UTC, merged